### ISSUE TITLE
How often should we update our app that has castore installed?

### ISSUE THREAD

**Issue by blisscs** [ericmj/castore#13]
Hi, 

I am seeing from the commit log, that the certificate file `priv/cacerts.pem` is getting updated from time to time. And along with the change to the file, new a version is also released.

I am wondering about how often, shall we update `castore` package that is installed in mix application, so that the running application should never have a certificate problem.

Thanks,
Dev.

**Comment by whatyouhide** [comment]
@blisscs ideally as much as possible. You could even go as far as checking if there is a new version every time you run CI to ensure you're up to date. An alternative you can try is [Dependabot](https://dependabot.com), which will automatically make a PR to your project when there's a new version of the package. Thanks for the issue! 💟
