### ISSUE TITLE
How often is the CA certificate store updated?

### ISSUE THREAD

**Issue by MichaelViveros** [ericmj/castore#14]
Just wondering how often the CAs are updated? And how do you know when to update? I want to use CAStore to get the latest Mozilla CA certificates and I'm not sure if I can rely on a new version of CAStore being released every time Mozilla's list is updated or if I should instead rely on `mix certdata` to always be up-to-date.

**Comment by whatyouhide** [comment]
@MichaelViveros we have Travis set up with a cron job that checks for updated certificates every day, so that's roughly how often it will get updated in case the certificate store gets updated. :)
